### ISSUE TITLE
ansible playbook failing with ssh key error

### ISSUE THREAD

**Issue by mramanathan** [abrahamvarricatt/ansible-demo-debug#1]
Hi Abraham,

In my local Ubuntu desktop, followed the steps to install the tool and finally ended up with error while running ansible-playbook. Do you know what's gone wrong here ?

> raman@homubuntu:~/ansible_demo/ansible-demo-debug/provision$ sudo ansible-playbook site.yml -i inventories/vagrant
> . . . . 
> TASK [setup] *******************************************************************
> **fatal: [192.168.77.10]: FAILED! => {"failed": true, "msg": "ERROR! to use the 'ssh' connection type with > passwords, you must install the sshpass program"**}

Tried the same after installing sshpass and now, it's cribbing of not using ssh key:

> TASK [setup] *******************************************************************
> fatal: [192.168.77.10]: FAILED! => {"failed": true, "msg": "ERROR! Using a SSH password instead of a > key is not possible because Host Key checking is enabled and sshpass does not support this.  Please 
> add this host's fingerprint to your known_hosts file to manage this host."}

Should playbook be executed from virtual machine env ?

**Comment by abrahamvarricatt** [comment]
@mramanathan, if you have ansible installed on your host system, there should be no need to use a virtualenv. Can you try running the command without sudo ?

Also - did you run 'vagrant up' ?

**Comment by mramanathan** [comment]
Right from the start, I have been using sudo because of this:

> raman@homubuntu:~/ansible_demo/ansible-demo-debug/provision$ vagrant status
> **> Vagrant failed to initialize at a very early stage:
> 
> The home directory you specified is not accessible. The home
> directory that Vagrant uses must be both readable and writable.
> You specified: /home/raman/.vagrant.d**

And, vagrant status is:

> raman@homubuntu:~/ansible_demo/ansible-demo-debug/provision$ sudo vagrant status
> Current machine states:
> 
> webapp                    running (virtualbox)
> The VM is running. To stop this VM, you can run `vagrant halt` to

**Comment by abrahamvarricatt** [comment]
Can we try shutting things down and starting from the beginning? One of the benefits of using vagrant is to avoid running with sudo. 

For now, to shut down (and destroy the virtual system)

```
$ sudo vagrant destroy
```

The above will remove all traces of the virtual system from your computer. At this point, can you delete the repository and make a new clone? I'm asking this because it is best if the commands are run without sudo. 

Here's what I suggest doing,

```
$ cd ~
$ mkdir ansible_demo
$ cd ansible_demo
$ git clone https://github.com/abrahamvarricatt/ansible-demo-debug.git
$ cd ansible-demo-debug
$ vagrant up
```

It might take some time, but the virtual system will be downloaded and brought up - you should NOT need to use sudo for any of these commands. Once the system is up you can SSH into the virtual system by running,

```
$ vagrant ssh
$ exit
```

then to exit the virutal system, run 'exit'. After that, you can power down the virtual system with,

```
$ vagrant halt
```

The above command will NOT delete the system, just power it off. 

Could you try these and tell me if they work as intended?  (also - what versions of vagrant, ansible and virtualbox are you using?)

**Comment by mramanathan** [comment]
Okay, will try and revert.

Package: ansible
Version: 2.0.0.2-2

Package: vagrant
Version: 1.8.1+dfsg-1

Package: virtualbox
Version: 5.0.24-dfsg-0ubuntu1.16.04.1

**Comment by abrahamvarricatt** [comment]
The versions look good. Am waiting to hear how things go after the revert - remember no sudo! :)

**Comment by mramanathan** [comment]
As per your suggestion, re-started everything from scratch. Able to run all vagrant commands without SUDO (had to change permissions of ~/.vagrant.d, made it 777)

Now with ansible-playbook there were errors with SSH being unable to read ~/.ansible. 
For this as well, I changed permissions of ~/.ansible and then re-ran the command:

This is the ssh-config:

$ vagrant ssh-config
Host webapp
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile "/home/raman/ansible_demo/ansible-demo-debug/.vagrant/machines/webapp/virtualbox/private_key"
  IdentitiesOnly yes
  LogLevel FATAL

$ sudo chmod -R 777 ~/.ansible/

$ ansible-playbook site.yml -i inventories/vagrant

> fatal: [192.168.77.10]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an 
> unknown error during the connection. We recommend you re-run the command using -vvvv, which will 
> enable SSH debugging output to help diagnose the issue", "unreachable": true}

Now, tried the same with "vvvv" option:

$ ansible-playbook -vvvv site.yml -i inventories/vagrant
Using /home/raman/ansible_demo/ansible-demo-debug/provision/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in site.yml

. . . . . 
<192.168.77.10> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.77.10> SSH: EXEC sshpass -d15 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/raman/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.77.10 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1473689968.3-171754224926214 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1473689968.3-171754224926214 )" )'
fatal: [192.168.77.10]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g-fips  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/raman/.ansible/cp/ansible-ssh-192.168.77.10-22-vagrant\" does not exist\r\ndebug2: resolving \"192.168.77.10\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 192.168.77.10 [192.168.77.10] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 192.168.77.10 port 22: Connection timed out\r\nssh: connect to host 192.168.77.10 port 22: Connection timed out\r\n", "unreachable": true}

**Comment by abrahamvarricatt** [comment]
Are you able to ssh into the virtual system?

i.e. 

```
$ cd /home/raman/ansible_demo/
$ vagrant ssh
```

and from your host, are you able to ping the system?

```
$ ping 192.168.77.10
```

The `vagrant up` command should setup the virtual system with IP = 192.168.77.10

**Comment by abrahamvarricatt** [comment]
Also - just sent a hangouts invite. Can we chat?

**Comment by mramanathan** [comment]
Oh, yes! Deleted $HOME/.vagrant.d and $HOME/.ansible and re-ran all the steps.

Voila, it works now !!!. Thanks Abraham.
