### ISSUE TITLE
webapp: Warning: Authentication failure. Retrying... ( In OSX )

### ISSUE THREAD

**Issue by Tibingeo** [abrahamvarricatt/ansible-demo-debug#3]
I have cloned the repo and executed vagrant up it give me following error 

```
webapp: Adapter 1: nat
webapp: Adapter 2: hostonly
```

==> webapp: Forwarding ports...
    webapp: 22 (guest) => 2222 (host) (adapter 1)
==> webapp: Running 'pre-boot' VM customizations...
==> webapp: Booting VM...
==> webapp: Waiting for machine to boot. This may take a few minutes...
    webapp: SSH address: 127.0.0.1:2222
    webapp: SSH username: vagrant
    webapp: SSH auth method: private key
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: 
    webapp: Vagrant insecure key detected. Vagrant will automatically replace
    webapp: this with a newly generated keypair for better security.
    webapp: 
    webapp: Inserting generated public key within guest...
    webapp: Removing insecure key from the guest if it's present...
    webapp: Key inserted! Disconnecting and reconnecting using new SSH key...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...

```
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
webapp: Warning: Authentication failure. Retrying...
```

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
![screen shot 2016-09-16 at 5 12 23 pm](https://cloud.githubusercontent.com/assets/16147643/18584803/c282315e-7c30-11e6-8672-6e7c5c57084f.png)

**Comment by pfrcks** [comment]
Facing the same issue

**Comment by abrahamvarricatt** [comment]
Can't say I've encountered this issue before. What version of virtualbox and vagrant do you have installed?

i.e. after running,

```
$ vboxmanage --version
$ vagrant --version
```

What output are you seeing?

**Comment by abrahamvarricatt** [comment]
On our meetup page, @Yasar suggested that this might due to vagrant. The fix suggested ( https://github.com/mitchellh/vagrant/issues/7610 ) is to update the permissions on the ssh authorization file by running,

```
$ chmod 0600 ~/.ssh/authorized_keys
```

Another approach is to just use an older version of vagrant. Uninstall instructions are here,
https://www.vagrantup.com/docs/installation/uninstallation.html

and older setups (I'm using vagrant 1.8.1) are here,
https://releases.hashicorp.com/vagrant/

**Comment by Tibingeo** [comment]
My virtual box version is 5.0.20
and Vagrant 1.8.5
@abraham downgrading vagrant to 1.8.1 did not fixed the issue for me

**Comment by abrahamvarricatt** [comment]
@Tibingeo what about the chmod suggestion?

**Comment by Tibingeo** [comment]
yea I even tried to change permission to 0600, getting same error btw

**Comment by abrahamvarricatt** [comment]
can you please paste a full dump of the output from when you start running `vagrant up` ?

**Comment by Tibingeo** [comment]
``` im0727-w0:ansible-demo-debug tibingeo$ vagrant up
Bringing machine 'webapp' up with 'virtualbox' provider...
==> webapp: Importing base box 'bento/centos-7.2'...
==> webapp: Matching MAC address for NAT networking...
==> webapp: Checking if box 'bento/centos-7.2' is up to date...
==> webapp: Setting the name of the VM: ansible-demo-debug_webapp_1474035946353_29452
==> webapp: Fixed port collision for 22 => 2222. Now on port 2201.
==> webapp: Clearing any previously set network interfaces...
==> webapp: Preparing network interfaces based on configuration...
    webapp: Adapter 1: nat
    webapp: Adapter 2: hostonly
==> webapp: Forwarding ports...
    webapp: 22 (guest) => 2201 (host) (adapter 1)
==> webapp: Running 'pre-boot' VM customizations...
==> webapp: Booting VM...
==> webapp: Waiting for machine to boot. This may take a few minutes...
    webapp: SSH address: 127.0.0.1:2201
    webapp: SSH username: vagrant
    webapp: SSH auth method: private key
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: Warning: Remote connection disconnect. Retrying...
    webapp: 
    webapp: Vagrant insecure key detected. Vagrant will automatically replace
    webapp: this with a newly generated keypair for better security.
    webapp: 
    webapp: Inserting generated public key within guest...
    webapp: Removing insecure key from the guest if it's present...
    webapp: Key inserted! Disconnecting and reconnecting using new SSH key...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying... 
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
    webapp: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value. ```

**Comment by abrahamvarricatt** [comment]
I'm wondering if (from the earlier attempt) you have a box running within that folder. Can you tell me the output of,

```
$ vagrant status
```

**Comment by Tibingeo** [comment]
im0727-w0:ansible-demo-debug tibingeo$ vagrant status
Current machine states:

webapp                    running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

**Comment by abrahamvarricatt** [comment]
That might be what's causing some of the trouble (It didn't get initialized properly). 
You can run,

```
$ vagrant destroy
```

to completly destroy the virtual image. And then try running,

```
$ vagrant up
```

again. (And please, when you run `vagrant up` this time, please share the output again. 

If you are on gmail, we can try to chat via hangouts. My id is: <email removed>

NOTE: I'll edit out that email from this comment within an hour.

**Comment by Tibingeo** [comment]
ok i'll get you in hangouts

**Comment by Tibingeo** [comment]
Issue fixed. changed vagrant file 

 # -_\- mode: ruby -_-
 # vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.ssh.insert_key = false

  # Create central management system
  config.vm.define :webapp do |webapp_config|
    webapp_config.vm.box = "bento/centos-7.2"
    webapp_config.vm.hostname = "webapp"
    webapp_config.vm.network "private_network", ip: "192.168.77.10"
    webapp_config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

end

**Comment by pfrcks** [comment]
I changed the file contents, but I'm still facing the same issue

**Comment by abrahamvarricatt** [comment]
@pfrcks you need to run 'vagrant destroy' to remove the old system first. After that, trying 'vagrant up' should work.
